### ISSUE TITLE
Dockerfile

### ISSUE THREAD

**Issue by pveber** [flass/pantagruel#11]
Use [the install script](https://github.com/flass/pantagruel/blob/master/install_dependencies.sh) for that.

**Comment by flass** [comment]
(rephrasing to external readers:)
We should soon release a Docker instance that contains all the dependencies (so no need to install anything), within which you will be able to run Pantagruel scripts (i.e. execute the commands `pantagruel --options TASK`).
Further integration of the Pantagruel pipeline into a Docker or Singularity container will later follow, so that the runtime is also handled, making the containers more like proper apps.

**Comment by samlipworth** [comment]
Is the docker instance ready yet/any idea when it will be?

**Comment by flass** [comment]
Dear Sam,
sorry for the wait. the Docker file is almost done. We were fighting with the integration of Interproscan (required for task 4), which we may have to exclude from the first packaged version. We should hopefully come back to you soon with the Dockerfile ready!
BW,
Florent

**Comment by bneron** [comment]
the container will be very helpful to run pantagruel on our cluster.
thank's
Bertrand

**Comment by pveber** [comment]
stay tuned, it's on its way :o)!

**Comment by matthieu-haudiquet** [comment]
> Dear Sam,
> sorry for the wait. the Docker file is almost done. We were fighting with the integration of Interproscan (required for task 4), which we may have to exclude from the first packaged version. We should hopefully come back to you soon with the Dockerfile ready!
> BW,
> Florent

If it's of any help :-)

https://github.com/Micromeda/InterProScan-Docker

https://github.com/biocorecrg/interproscan_docker/blob/master/Singularity

**Comment by flass** [comment]
:whale: The Dockerfile is now available!

Use it to generate a Docker image containing all Pantagruel dependencies; then use that image to run `pantagruel` commands within the environment provided by the container, as explained [here](https://github.com/flass/pantagruel/blob/master/INSTALL.md#the-container-worryless-way).  
NB: this may be used to generate a Singularity container as well, even though it was not tested yet

The Docker image is being validated (currently fixing task 08, but that's only at the pipeline script level, the dependencies and thus the Docker image are fine); once this is done, I'll consider providing an already compiled image (e.g. via [dockerhub](https://hub.docker.com/)).

Feel free to comment and post issue regarding the use of the container version!
