### ISSUE TITLE
task 0 failed

### ISSUE THREAD

**Issue by kuzman1306** [flass/pantagruel#16]
Hi Florent,

I successfully make config file and tried to run all pantagruel tasks. However, I am getting the following error with task 0:
```
'pantagruel -i /home/kuzman/agrobacterium/environ_pantagruel_agrobacterium.sh all
This is Pantagruel pipeline version 8fa4a2d45b2c172b748f3783001da2a56bb68f97 using source code from repository '/home/kuzman/pantagruel_pipeline/pantagruel'
# will run tasks: 0 1 2 3 4 5 6 7 8 9
[2019-08-03 14:13:01] Pantagrel pipeline task 0: fetch public genome data from NCBI sequence databases and annotate private genomes.
Create new task folder '/home/kuzman/agrobacterium/00.input_data'
[2019-08-03 14:13:02] extract assembly data from folder '/home/kuzman/agrobacterium_genomes'
found 6 contig files (raw genome assemblies) in /home/kuzman/agrobacterium_genomes/contigs/
[2019-08-03 14:13:02] a1
found annotation folder '/home/kuzman/agrobacterium_genomes/annotation/a1' ; skip annotation of contigs in '/home/kuzman/agrobacterium_genomes/contigs/a1.fasta'
ln: failed to create symbolic link '/home/kuzman/agrobacterium/00.input_data/annotation/': File exists
fix annotation to integrate region information into GFF files
ls: cannot access '/home/kuzman/agrobacterium/00.input_data/annotation/a1/*.gff': No such file or directory
Error: missing mandatory GFF file in /home/kuzman/agrobacterium/00.input_data/annotation/a1/ folder
ERROR: Pantagrel pipeline task 0: failed.'
```
I downloaded *.gif and *.fasta files from NCBI genebank. Please find attached input files, including config file.

I also tried to run test, but also getting the error in task 0. I also attached error text and log file (test_error.zip).

I think I have installed correctly all dependencies (log file attached).

Do you maybe have an idea what could be the problem?

I look forward to hearing from you.

Cheers,

Nemanja

[dependencies.txt](https://github.com/flass/pantagruel/files/3463805/dependencies.txt)

[test_error.zip](https://github.com/flass/pantagruel/files/3463804/test_error.zip)

[input.zip](https://github.com/flass/pantagruel/files/3463798/input.zip)

**Comment by kuzman1306** [comment]
Hi Florent,

In the meantime, I manually installed all dependencies and successfully initiated pipeline. Although it reached task 5, there were some errors in task 2, which affected task 5 to fail. I am not sure what could be the problem. Please find attached the file including all steps.

Cheers,

Nemanja

[log.txt](https://github.com/flass/pantagruel/files/3465319/log.txt)

**Comment by flass** [comment]
Hi Nemanja,
You have a first error at line 476, in the task 01. I believe this to relate to the problem identified at the end of the issue thread #12 : the version of MMseqs that is now automatically installed with Homebrew is different that the one I developed the scripts with, and the format of the output has changed; therefore the output files are not parsed correctly and subsequent tasks fail.
I'll try and upgrade the task 01 scripts today so that pantagruel can handle the version 9 of MMseqs.

Can you please have a look to what is the version your MMseqs, just to be sure it is the actual issue?
Thanks
Florent

**Comment by flass** [comment]
hi again, this should be resolved, see #12.

**Comment by flass** [comment]
and regarding the first bug that you reported during Prokka annotation, a fix should be provided with ee23e3d.

**Comment by kuzman1306** [comment]
Hi Florent,
It works now.
Thanx.
Cheers,
Nemanja

**Comment by flass** [comment]
brilliant!
