### ISSUE TITLE
links in generated outputs

### ISSUE THREAD

**Issue by pveber** [flass/pantagruel#2]
In step 0 (among others), we create symbolic links to input data. It would help to create *relative* links instead of absolute. This is necessary for bistro integration and better in general (an analysis directory can then be moved around without breaking links). This can be done with `realpath`, see [this example](https://stackoverflow.com/questions/2564634/convert-absolute-path-into-relative-path-given-a-current-directory-using-bash).

**Comment by flass** [comment]
very good point! 
this has been fixed thoughout the pipeline in commit 0167cdd using code like `ln -s $(realpath --relative-to=$(dirname dest) src) dest`
Cheers!
Florent
