### ISSUE TITLE
pantagruel_pipeline_00_fetch_data.sh

### ISSUE THREAD

**Issue by samlipworth** [flass/pantagruel#20]
/home/sam/pantagruel_pipeline/pantagruel/scripts/pipeline/pantagruel_pipeline_00_fetch_data.sh: line 356: unexpected EOF while looking for matching `''
/home/sam/pantagruel_pipeline/pantagruel/scripts/pipeline/pantagruel_pipeline_00_fetch_data.sh: line 359: syntax error: unexpected end of file

fixed by closing the quotations in the grep command

**Comment by flass** [comment]
Hi Sam,

thanks for reporting. This was fixed in the subsequent commit 0c77f87 ; the fix should already be integrated if you use the last version.

**Comment by samlipworth** [comment]
Ah ok thanks - I recloned and started again yesterday so not sure how I didn't end up with the latest version.
