### ISSUE TITLE
Java version and InterProScan

### ISSUE THREAD

**Issue by ElitaJaun** [flass/pantagruel#3]
Hi Florent, 

Seem that Java version needs updating to run with InterProScan. Would you please be able to help out with this? 

I get the following message:

pantagruel_pipeline/pantagruel/install_dependencies.sh: line 248: [: too many arguments
Java version 1.8 is required to run InterProScan.
Detected version 10.0
Please install the correct version.
ERROR: Interproscan test was not successful

**Comment by flass** [comment]
OK this is due to a small bug introduced in previous commit 3be7cea to fix installation of Interproscan.
This should be fixed with commit 5021d45. Please let me know.

**Comment by ElitaJaun** [comment]
Thank you - the java error has disappeared, I thought id better install it all again and Java error disappeared, but I now getting the following:
 
pantagruel_pipeline/pantagruel/install_dependencies.sh: line 212: interproscan: command not found
get Interproscan 5.33-72.0
found InterProScan executable:
/home/elita/pantagruel_pipeline/interproscan-5.33-72.0/interproscan.sh
22/02/2019 14:54:01:936 Welcome to InterProScan-5.33-72.0
usage: java -XX:+UseParallelGC -XX:ParallelGCThreads=2 -XX:+AggressiveOpts
            -XX:+UseFastAccessorMethods -Xms128M -Xmx2048M -jar
            interproscan-5.jar

then all option for analyses and it ends with this
ERROR: Interproscan test was not successful

Do I need to do anything about this?

**Comment by flass** [comment]
this was a bug in the installation script. This is fixed with commit 99deaa4.
