### ISSUE TITLE
Task 04 failed: InterProScan version check

### ISSUE THREAD

**Issue by mattbawn** [flass/pantagruel#46]
Hi Florent,

Is there a way to force pantagruel to accept the installed interproscan version:

```
Error: the installed version of InterProScan (found at /pantagruel/interproscan-5.46-81.0/interproscan.sh is '5.46-81.0', different from the version currently published on the EBI FTP: ''.
```

btw I think the installed version _is_ the current version, its just my cluster is closed so pantagruel can't see whats on EBI FTP.

Thanks,

Matt

**Comment by flass** [comment]
Hi Matt,

sorry about that, there was an error in the escape to the version verification test in the event you can't reach the FTP server.
It's now fixed ([usingGeneRax d7aafe1] and [master f1fb98c]) in the code, dockerhub image builds are to follow shortly.
