### ISSUE TITLE
Error while installing dependencies

### ISSUE THREAD

**Issue by jhcuarta** [flass/pantagruel#49]
Hi

I got the following error while trying to install dependencies

Reading package lists... Done
Building dependency tree       
Reading state information... Done
11 packages can be upgraded. Run 'apt list --upgradable' to see them.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'python-is-python2' instead of 'python'
Package python-scipy is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

Package python-pip is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  python3-pip

E: Package 'python-scipy' has no installation candidate
E: Unable to locate package python-biopython
E: Unable to locate package python-biopython-sql
E: Unable to locate package python-igraph
E: Package 'python-pip' has no installation candidate
E: Unable to locate package linuxbrew-wrapper
E: Unable to locate package docker\.io
ERROR: could not install all required Debian packages:
Listing... Error!
build-essential/focal-updates,now 12.8ubuntu1.1 amd64 [installed]
build-essential/focal-updates 12.8ubuntu1.1 i386
clustalo/focal,now 1.2.4-4build1 amd64 [installed,automatic]
cmake/focal 3.16.3-1ubuntu1 amd64
cmake/focal 3.16.3-1ubuntu1 i386
cython/focal 0.29.14-0.1ubuntu3 amd64
cython/focal 0.29.14-0.1ubuntu3 i386
g++/focal,now 4:9.3.0-1ubuntu2 amd64 [installed]
g++/focal 4:9.3.0-1ubuntu2 i386
gcc/focal,now 4:9.3.0-1ubuntu2 amd64 [installed]
gcc/focal 4:9.3.0-1ubuntu2 i386
gfortran/focal,now 4:9.3.0-1ubuntu2 amd64 [installed,automatic]
gfortran/focal 4:9.3.0-1ubuntu2 i386
git/focal-updates,focal-security 1:2.25.1-1ubuntu3.4 amd64 [upgradable from: 1:2.25.1-1ubuntu3.3]
git/focal-updates,focal-security 1:2.25.1-1ubuntu3.4 i386
lftp/focal,now 4.8.4-2build3 amd64 [installed]
libdw-dev/focal 0.176-1.1build1 amd64
libdw-dev/focal 0.176-1.1build1 i386
libdw1/focal,now 0.176-1.1build1 amd64 [installed,automatic]
libdw1/focal 0.176-1.1build1 i386
libgsl-dev/focal,now 2.5+dfsg-6build1 amd64 [installed]
libgsl-dev/focal 2.5+dfsg-6build1 i386
libgsl23/focal,now 2.5+dfsg-6build1 amd64 [installed,automatic]
libgsl23/focal 2.5+dfsg-6build1 i386
libhmsbeagle1v5/focal 3.1.2+dfsg-7build1 amd64
libmagick++-dev/focal-updates,focal-updates,focal-security,focal-security,now 8:6.9.10.23+dfsg-2.1ubuntu11.4 all [installed]
mpi-default-bin/focal 1.13 amd64
mpi-default-bin/focal 1.13 i386
mpi-default-dev/focal 1.13 amd64
mpi-default-dev/focal 1.13 i386
mrbayes-mpi/focal 3.2.6+dfsg-2ubuntu2 amd64
mrbayes/focal 3.2.6+dfsg-2ubuntu2 amd64
openjdk-11-jdk/focal-updates,focal-security 11.0.15+10-0ubuntu0.20.04.1 amd64
openjdk-11-jdk/focal-updates,focal-security 11.0.15+10-0ubuntu0.20.04.1 i386
openjdk-11-jre/focal-updates,focal-security 11.0.15+10-0ubuntu0.20.04.1 amd64 [upgradable from: 11.0.14.1+1-0ubuntu1~20.04]
openjdk-11-jre/focal-updates,focal-security 11.0.15+10-0ubuntu0.20.04.1 i386
python-numpy/focal 1:1.16.5-2ubuntu7 amd64
r-base-core/focal-cran40,now 4.1.3-1.2004.0 amd64 [installed]
r-cran-ade4/focal 1.7-18-1cran1.2004.0 amd64
r-cran-ape/focal 5.6-2-1cran1.2004.0 amd64
r-cran-dbi/focal,focal 1.1.2-1cran1.2004.0 all
r-cran-getopt/focal,focal 1.20.3-2.1~ubuntu20.04.1~ppa1 all
r-cran-igraph/focal 1.3.0-1cran1.2004.0 amd64
r-cran-phytools/focal,focal 1.0-3-1cran1.2004.0 all
r-cran-rcolorbrewer/focal,focal,now 1.1-3-1cran1.2004.0 all [installed,automatic]
r-cran-rsqlite/focal 2.2.12-1cran1.2004.0 amd64
r-cran-vegan/focal 2.5-7-1cran1.2004.0 amd64
r-recommended/focal-cran40,now 4.1.3-1.2004.0 all [installed,automatic]
raxml/focal,now 8.2.12+dfsg-4 amd64 [installed,automatic]
sqlite3-doc/focal-updates,focal-updates,focal-security,focal-security 3.31.1-4ubuntu0.2 all
sqlite3/focal-updates,focal-security 3.31.1-4ubuntu0.2 amd64
sqlite3/focal-updates,focal-security 3.31.1-4ubuntu0.2 i386
E: input:0-10: error: Expected pattern
   docker\.io
   ^^^^^^^^^^
ERROR: abort installation of Pantagruel

**Comment by flass** [comment]
Hi,
this looks like an issue due to the obsolescence of Python 2. As Pantagruel relies on Python 2.7, it aims to have it installed and so the dependency installation script relied on `apt` to install the relevant Debian packages. however, with the recent  effective retirement of Python 2 in modern Linux operating systems, these packages may not be available anymore. 
Can you please specify what operating system you're using? I suspect it is too recent.
Pantagruel has been tested on Ubuntu 18.4 LTS the install script was meant to be used on this system; sorry this was not made clear in the doc.
This was now clarified in the INTALL doc (see ac69b4a).

to solve your issue, I recommend you do one of these things:
- try and install Pantagruel on a machine with Ubuntu 18.4 LTS (this can be easily achieved by spinning a VM with this OS flavour)
- use the Docker image provided on Dockerhub (https://hub.docker.com/repository/docker/flass/pantagruel-dep) to run Pantagruel (this image has been built on Ubuntu 18.4 LTS base).

I hope this helps.

Best wishes,

Florent

**Comment by flass** [comment]
I close this as I consider it resolved but if the suggested approach did not work please reopen the issue.
