### ISSUE TITLE
Usage: errors when using pantagruel command with TASKS

### ISSUE THREAD

**Issue by ElitaJaun** [flass/pantagruel#5]
Hi Florent, 

I got the following error when running command pantagruel -i /environ_pantagruel_databasename.sh fetch

This is Pantagruel pipeline version 02fa4e538118cb231a3f843d57b21685db538777 using source code from repository '/home/elita/pantagruel_pipeline/pantagruel'
# will run tasks: 0
[2019-03-05 16:27:19] Pantagrel pipeline step 0: fetch public genome data from NCBI sequence databases and annotate private genomes.
did not find the relevant taxonomy flat files in '/home/elita/NCBI/Taxonomy_2019-03-05/'; download the from NCBI Taxonomy FTP
cd ok, cwd=/pub/taxonomy                                 
55885994 bytes transferred in 10 seconds (5.30 MiB/s)               
Total 6 files transferred
taxcat.tar.gz: OK
taxdump.tar.gz: OK
/home/elita
extract assembly data from folder '/home/elita/gbs_ncbi'
/home/elita/pantagruel_pipeline/pantagruel/scripts/pipeline/pantagruel_pipeline_00_fetch_data.sh: line 264: /home/elita/databasename/00.input_data/genome_infos/assemblies_list: No such file or directory
Traceback (most recent call last):
  File "/home/elita/pantagruel_pipeline/pantagruel/scripts/check_create_cds_from_genomic.py", line 22, in <module>
    with open(nfldirassemb, 'r') as fldirassemb:
IOError: [Errno 2] No such file or directory: '/home/elita/databasename/00.input_data/genome_infos/assemblies_list'
/home/elita/pantagruel_pipeline/pantagruel/scripts/pipeline/pantagruel_pipeline_00_fetch_data.sh: line 288: /home/elita/pantagruel_pipeline/pantagruel/scripts/groom_refseq_data.sh/home/elita/databasename/00.input_data/assemblies: Not a directory
Traceback (most recent call last):
  File "/home/elita/pantagruel_pipeline/pantagruel/scripts/extract_metadata_from_gbff.py", line 77, in <module>
    with open(nfldirassemb, 'r') as fldirassemb:
IOError: [Errno 2] No such file or directory: '/home/elita/databasename/00.input_data/genome_infos/assemblies_list'
ERROR: 

Any advise? Thanks. 

bw, 
Elita

**Comment by flass** [comment]
Hi Elita,
well spotted! it's due to a change I had just introduced. it si fixed in commits 6cef840, 843ba27 and dd65fb2.
