### ISSUE TITLE
Usage: task 5 error

### ISSUE THREAD

**Issue by ElitaJaun** [flass/pantagruel#7]
Dear Florent, 

Tasks/steps  0-4 seem to be working fine, but when I get to task 5 I get the following error:

Traceback (most recent call last):
  File "/home/elita/pantagruel_pipeline/pantagruel/scripts/replace_species_by_pop_in_gene_trees.py", line 3, in <module>
    import tree2
ImportError: No module named tree2
tail: cannot open '/home/elita/databasename/05.core_genome/core-genome-based_reference_tree_databasename_populations' for reading: No such file or directory
Found 0 disctinct populations in the species tree
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named tree2
ERROR: 

Thank you. 

Bw, 
Elita

**Comment by flass** [comment]
Hi Elita,
OK so the tree2 python package is not seen. It should be installed with the [install_dependencies.sh](https://github.com/flass/pantagruel/blob/master/install_dependencies.sh) script, and its location should be added to your `$PYTHONPATH` environement variable through editing of your `~/.bashrc` file.
Now I realize it may be that you provided a relative path for the target installation directory (argument of `install_dependencies.sh`), which might result in the `$PYTHONPATH` being defined but not pointing to an absolute path and thus in most cases, not the correct place.
Can you please provide the value of this variable?
Best wishes,
Florent

**Comment by flass** [comment]
I realize the situation described above could happen if you installed the software with a previous version, before I enforced the interpretation of relative paths into absolute paths (see similar point in #4). I added a more stringent test on the previous presence of `$PYTHONPATH` definition in `~/.bashrc` in commit 4a4b63d.
If that was the case, please either  re-run the install script, or just edit your `~/.bashrc` so to have absolute path in the `$PYTHONPATH` definition.

**Comment by flass** [comment]
This possibility of bug should now be completely avoided through the integration of the [tree2 git repository](https://github.com/flass/tree2) as a submodule of this repo (commits 7a71315, bdebd1a and 7a8c449).
